Description:  Cloudformation Template to install Jenkins
Resources:
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: 
      - S3_access
  EC2Instance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          jenkinsinstall:
          - update_system
          - install_cfn
          - repo_and_packages
          - upgrade_system
          - software_install
        update_system:
          commands:
            update: 
              command: yum update -y
        install_cfn:
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack= ${AWS::StackId}
                region=${AWS::Region}
              group: root
              mode: '000400'
              owner: root
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.EC2Instance.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2Instance --configsets wordpress_install --region ${AWS::Region}
              group: root
              mode: '000400'
              owner: root
          services:
            sysvinit:
              cfn-hup:
                enabled: true
                ensureRunning: true
                files:
                - /etc/cfn/cfn-hup.conf
                - /etc/cfn/hooks.d/cfn-auto-reloader.conf
        repo_and_packages:
          commands:
            wget:
              command: |
                sudo wget -O /etc/yum.repos.d/jenkins.repo \
                https://pkg.jenkins.io/redhat-stable/jenkins.repo
            import_key:
              command: sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        upgrade_system:
          commands:
            upgrade: 
              command: sudo yum upgrade -y 
        software_install:
          commands:
            01_install_java: 
              command: sudo dnf install java-17-amazon-corretto -y
            02_install_jenkins: 
              command: sudo yum install jenkins -y
            03_start_jenkins:
              command: sudo systemctl start jenkins 
            04_enable_jenkins:
              command: sudo systemctl enable jenkins
            05_Jenkins_pass:
              command: sudo aws s3 cp /var/lib/jenkins/secrets/initialAdminPassword s3://cloudformation-init/jenkins-password.txt  && echo /var/lib/jenkins/secrets/initialAdminPassword 
    Properties:
      InstanceType: "t2.micro"
      ImageId: ami-0ae8f15ae66fe8cda
      KeyName: Vinit
      SecurityGroupIds:
      - sg-05b22a54bd55633d0
      IamInstanceProfile: s3_access
      Tags:
        - Key: Name
          Value: JENKINS_INSTANCE
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
           yum install -y aws-cli
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackId} --resource EC2Instance --configsets jenkinsinstall --region ${AWS::Region}
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource EC2Instance --region ${AWS::Region}


Outputs:
  JenkinsURL:
    Description: Url for Jenkins
    Value: !Sub "http://${EC2Instance.PublicIp}:8080"
    Export:
      Name: URLnew
  JenkinsPasswordS3Url:
    Description: URL of the Jenkins password in S3
    Value: !Sub "https://s3.amazonaws.com/clouformation-init/jenkins-password.txt"
    Export:
      Name: JenkinsFirstLoginPasswordnew

